CREATE TABLE IF NOT EXISTS employees (
    employee_id VARCHAR(255) NOT NULL,
    name VARCHAR(255) NOT NULL,
    department VARCHAR(255) NOT NULL,
    role VARCHAR(255) NOT NULL,
    status VARCHAR(255) NOT NULL,
    PRIMARY KEY (employee_id)
);

CREATE TABLE IF NOT EXISTS accounts (
    account_id VARCHAR(255) NOT NULL,
    employee_id VARCHAR(255) NOT NULL,
    username VARCHAR(255) NOT NULL,
    status VARCHAR(255) NOT NULL,
    PRIMARY KEY (account_id)
);

CREATE TABLE IF NOT EXISTS application_access (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    employee_id VARCHAR(255) NOT NULL,
    application VARCHAR(255) NOT NULL,
    access_level VARCHAR(255) NOT NULL,
    status VARCHAR(255) NOT NULL,
    expires_at TIMESTAMP WITH TIME ZONE,
    PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS emails (
    employee_id VARCHAR(255) NOT NULL,
    email_address VARCHAR(255) NOT NULL,
    PRIMARY KEY (employee_id)
);

CREATE TABLE IF NOT EXISTS resources (
    resource_id VARCHAR(255) NOT NULL,
    employee_id VARCHAR(255) NOT NULL,
    resource_type VARCHAR(255) NOT NULL,
    status VARCHAR(255) NOT NULL,
    PRIMARY KEY (resource_id)
);

CREATE TABLE IF NOT EXISTS workflow_executions (
    workflow_id VARCHAR(255) NOT NULL,
    workflow_type VARCHAR(255) NOT NULL,
    employee_id VARCHAR(255),
    status VARCHAR(255) NOT NULL,
    failed_step VARCHAR(255),
    failure_reason VARCHAR(1000),
    summary VARCHAR(5000),
    executed_at VARCHAR(255) NOT NULL,
    duration_ms BIGINT,
    PRIMARY KEY (workflow_id)
);

CREATE TABLE IF NOT EXISTS approval_requests (
    request_id VARCHAR(255) NOT NULL,
    requester VARCHAR(255) NOT NULL,
    idempotency_key VARCHAR(255),
    operation VARCHAR(255) NOT NULL,
    request_payload VARCHAR(20000) NOT NULL,
    risk_level VARCHAR(255) NOT NULL,
    risk_score INTEGER NOT NULL,
    status VARCHAR(255) NOT NULL,
    policy_decision VARCHAR(255) NOT NULL,
    violations VARCHAR(4000),
    first_approver VARCHAR(255),
    second_approver VARCHAR(255),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    workflow_id VARCHAR(255),
    PRIMARY KEY (request_id),
    CONSTRAINT uk_approval_idempotency UNIQUE (idempotency_key)
);

CREATE TABLE IF NOT EXISTS audit_events (
    event_id VARCHAR(255) NOT NULL,
    request_id VARCHAR(255),
    workflow_id VARCHAR(255),
    actor VARCHAR(255) NOT NULL,
    actor_type VARCHAR(255) NOT NULL,
    agent_name VARCHAR(255),
    event_type VARCHAR(255) NOT NULL,
    action VARCHAR(255) NOT NULL,
    decision VARCHAR(255) NOT NULL,
    details VARCHAR(5000),
    occurred_at TIMESTAMP WITH TIME ZONE NOT NULL,
    PRIMARY KEY (event_id)
);

CREATE TABLE IF NOT EXISTS external_access_grants (
    grant_id VARCHAR(255) NOT NULL,
    employee_id VARCHAR(255) NOT NULL,
    application VARCHAR(255) NOT NULL,
    access_level VARCHAR(255) NOT NULL,
    status VARCHAR(255) NOT NULL,
    expires_at TIMESTAMP WITH TIME ZONE,
    PRIMARY KEY (grant_id)
);

CREATE TABLE IF NOT EXISTS remediation_tasks (
    task_id VARCHAR(255) NOT NULL,
    finding_code VARCHAR(255) NOT NULL,
    employee_id VARCHAR(255) NOT NULL,
    action VARCHAR(1000) NOT NULL,
    severity VARCHAR(255) NOT NULL,
    disposition VARCHAR(255) NOT NULL,
    status VARCHAR(255) NOT NULL,
    approved_by VARCHAR(255),
    last_error VARCHAR(2000),
    created_at TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL,
    PRIMARY KEY (task_id)
);